name: clean_architecture_poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^10.0.0
  get_it: ^7.6.0
  go_router: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  random_name_generator: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
